name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/pastebin
            git pull origin main
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ice1one --password-stdin
            docker compose pull app
            docker compose up -d --no-deps app
            docker image prune -f
